### PR TITLE
Salted hashed passwords using argon2

### LINKED ISSUE #513: [Security] Password storage is insecure
**Describe the bug**
Passwords are hashed but not salted.

**Expected behavior**
Good password hash+salt algorithm.

**Additional context**

### PR DESCRIPTION
**Pull request by etnoy**
This pull request adds salted passwords using the work function argon2 as well as utf8 database support and a number of new tests.

The only thing missing now is 4-byte character support in usernames.

This pull request includes my previous pull request 511.

This fixes #513 and #509

### CODE REVIEW

File: src/main/java/dbProcs/Getter.java [hunk 1]
```diff
@@ -65,96 +76,142 @@
...
-			{
-				log.debug("User did not exist");
-				userFound = false;
+			userFind = callstmt.executeQuery();
+		} catch (SQLException e) {
+			log.fatal("Could not create call statement: " + e.toString());
+			throw new RuntimeException(e);
+		}
+
+		log.debug("Opening Result Set from userFind");
```
Comment (markdenihan) [inline src/main/java/dbProcs/Getter.java]: If we're removing the "userFind" stored procedure from the authUser message, the logging should be updated to match

File: src/main/java/dbProcs/Getter.java [hunk 2]
```diff
@@ -65,96 +76,142 @@
...
+
+			log.debug("Getting password hash");
+			String dbHash;
+			try {
+				dbHash = userFind.getString(3);
+				log.debug("Verifying hash");
+
+				userVerified = argon2.verify(dbHash, password.toCharArray());
+
+				log.debug("Verification result: " + password);
```
Comment (markdenihan) [inline src/main/java/dbProcs/Getter.java]: We shouldn't log this

File: src/main/java/dbProcs/Getter.java [hunk 3]
```diff
@@ -1856,6 +1913,7 @@ public static String getUserClassFromName (String ApplicationRoot, String userNa
 	{
 		log.debug("*** Getter.getUserClass ***");
 		String result = new String();
+		userName=userName.toLowerCase();
```
Comment (markdenihan) [inline src/main/java/dbProcs/Getter.java:1908]: Why is this being added?

File: src/main/java/dbProcs/Getter.java [hunk 4]
```diff
@@ -1887,6 +1945,9 @@ public static String getUserIdFromName (String ApplicationRoot, String userName)
 	{
 		log.debug("*** Getter.getUserIdFromName ***");
 		String result = new String();
+		
+		userName=userName.toLowerCase();
```
Comment (markdenihan) [inline src/main/java/dbProcs/Getter.java:1941]: Why is this being added?

File: src/main/java/dbProcs/Setter.java [hunk 5]
```diff
@@ -282,6 +285,9 @@ public static boolean resetBadSubmission(String ApplicationRoot, String userId)
 	 */
 	public static boolean setCoreDatabaseInfo(String applicationRoot, String url, String userName, String password)
 	{
+		
+		userName=userName.toLowerCase();
```
Comment (markdenihan) [inline src/main/java/dbProcs/Setter.java:289]: Why is this being added?

File: src/main/resources/database/coreSchema.sql [hunk 6]
```diff
@@ -60,8 +61,8 @@ CREATE  TABLE IF NOT EXISTS `core`.`modules` (
   `moduleType` VARCHAR(16) NOT NULL ,
   `moduleCategory` VARCHAR(64) NULL ,
   `moduleCategoryLangPointer` VARCHAR(64) NULL ,
-  `moduleResult` VARCHAR(256) NULL ,
-  `moduleHash` VARCHAR(256) NULL UNIQUE,
+  `moduleResult` VARCHAR(191) NULL ,
+  `moduleHash` VARCHAR(191) NULL UNIQUE,
```
Comment (markdenihan) [inline src/main/resources/database/coreSchema.sql:65]: Why the reduction in memory?

File: src/main/resources/database/coreSchema.sql [hunk 7]
```diff
@@ -1781,8 +1760,8 @@ CREATE  TABLE IF NOT EXISTS `backup`.`modules` (
   `moduleName` VARCHAR(64) NOT NULL ,
   `moduleType` VARCHAR(16) NOT NULL ,
   `moduleCategory` VARCHAR(64) NULL ,
-  `moduleResult` VARCHAR(256) NULL ,
-  `moduleHash` VARCHAR(256) NULL ,
+  `moduleResult` VARCHAR(191) NULL ,
+  `moduleHash` VARCHAR(191) NULL ,
```
Comment (markdenihan) [inline src/main/resources/database/coreSchema.sql:1764]: Why the reduction in memory?

File: src/main/webapp/login.jsp [hunk 8]
```diff
@@ -41,6 +41,11 @@ if(request.getSession() != null)
 		
 	}
 }
+
+//Try talking to the database to force an early error if there's some db problem so we see error messages before trying to log in
+
+Connection conn = Database.getCoreConnection();
```
Comment (markdenihan) [inline src/main/webapp/login.jsp:47]: Should probably close connections here immediately afterwards?

File: src/main/webapp/setup.jsp [hunk 9]
```diff
@@ -93,23 +93,23 @@ if (Setup.isInstalled()) {
...
+								<input type="text" id="dbport" name="dbport" value="3306" required>
 							</div>
 						</div>
 						<div class="row">
 							<div class="col-25">
 								<label for="dbuser"><fmt:message key="generic.text.setup.user" /></label>
 							</div>
 							<div class="col-75">
-								<input type="text" id="dbuser" name="dbuser" placeholder="Shepherd Database User.." required>
+								<input type="text" id="dbuser" name="dbuser" value="root" required>
```
Comment (markdenihan) [inline src/main/webapp/setup.jsp]: This needs to be changed back to placeholders

Comment (markdenihan) [reply src/main/webapp/setup.jsp]: To be clear, don't mind the default values being there, but they should be placeholders not values

File: src/main/java/dbProcs/Getter.java [hunk 10]
```diff
@@ -65,96 +76,142 @@
...
+		CallableStatement callstmt;
+		try {
+			callstmt = conn.prepareCall(
+					"SELECT userId, userName, userPass, userRole, badLoginCount, tempPassword, classId, suspendedUntil FROM `users` WHERE userName = ?");
+		} catch (SQLException e) {
+			log.fatal("Could not retrieve users from database: " + e.toString());
+			throw new RuntimeException(e);
+		}
+
+		log.debug("Gathering userFind ResultSet");
```
Comment (markdenihan) [inline src/main/java/dbProcs/Getter.java]: Should update logging to reflect the dropped Stored Procedure

**Review by markdenihan — CHANGES_REQUESTED** [review]

**Comment by markdenihan** [comment]
@etnoy Is this still WIP or ready to merge?

File: src/main/java/dbProcs/Getter.java (hunk 1 above)
Comment (etnoy) [reply src/main/java/dbProcs/Getter.java]: Will do.

File: src/main/java/dbProcs/Getter.java (hunk 2 above)
Comment (etnoy) [reply src/main/java/dbProcs/Getter.java]: You're right, sorry

File: src/main/java/dbProcs/Getter.java (hunk 3 above)
Comment (etnoy) [reply src/main/java/dbProcs/Getter.java:1908]: To comply with OWASP auth recommendations to make usernames non-case-sensitive. Also, we've had this issue in our installs

File: src/main/java/dbProcs/Getter.java (hunk 4 above)
Comment (etnoy) [reply src/main/java/dbProcs/Getter.java:1941]: See above

File: src/main/java/dbProcs/Setter.java (hunk 5 above)
Comment (etnoy) [reply src/main/java/dbProcs/Setter.java:289]: See above

File: src/main/resources/database/coreSchema.sql (hunk 6 above)
Comment (etnoy) [reply src/main/resources/database/coreSchema.sql:65]: UTF-8 encoding requires 191 because four-byte chars on mysql 5.5 can't fit if mem > 191.

File: src/main/resources/database/coreSchema.sql (hunk 7 above)
Comment (etnoy) [reply src/main/resources/database/coreSchema.sql:1764]: See above

File: src/main/webapp/login.jsp (hunk 8 above)
Comment (etnoy) [reply src/main/webapp/login.jsp:47]: You're right

File: src/main/java/dbProcs/Getter.java (hunk 10 above)
Comment (etnoy) [reply src/main/java/dbProcs/Getter.java]: Good point

File: src/main/webapp/setup.jsp (hunk 9 above)
Comment (etnoy) [reply src/main/webapp/setup.jsp]: > @etnoy Is this still WIP or ready to merge?

No, not WIP anymore. I would say so if you're alright with the above comments not being fixed yet. Thanks for taking a look at my pull request.

**Comment by etnoy** [comment]
Just pushed commit with all your proposed fixes, @markdenihan. As soon as tests pass we should be good.

**Review by markdenihan — APPROVED** [review]

**Comment by markdenihan** [comment]
Thanks @etnoy for the Pull!
